import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
	const [queryResult, setQueryResult] = useState();
	// name, description, votesCount, thumbnail, reviewsRating
	const fetchProductHuntAPI = async () => {
		const response = await fetch("https://api.producthunt.com/v2/api/graphql", {
			method: "POST",
			headers: {
				Accept: "application/json",
				"Content-Type": "application/json",
				Authorization: `Bearer ${process.env.NEXT_PUBLIC_PRODUCT_HUNT_ACCESS_TOKEN}`,
				Host: "api.producthunt.com",
			},
			body: JSON.stringify({
				query: `query {
          posts(first: 50, order: VOTES) {
            edges {
              node {
                id
                name
                description
                website
                tagline
                topics {
                  edges {
                    node {
                      name
                    }
                  }
                }
                thumbnail {
                  url
                }
                makers {
                  name
                }
              }
            }
          }
        }`,
			}),
		});
		console.log(
			response.headers.forEach((val, name) => {
				console.log(name + ": " + val);
			})
		);
		const data = await response.json();
		console.log(data);
		const contents = data.data.posts.edges;
		// item.node

		setQueryResult(contents);
		console.log(queryResult);
	};

	useEffect(() => {
		fetchProductHuntAPI();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Hello World</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className="text-6xl font-bold text-center">Lai Jian Shin's</h1>
				<h1 className="text-5xl font-medium text-center"> GraphQL</h1>

				<p className={styles.description}>
					Made exclusively with NextJS and Tailwind CSS
				</p>

				<div className="container mx-auto">
					<div className="grid gap-y-8 grid-cols-1 md:grid-cols-3 2xl:grid-cols-4">
						{queryResult &&
							queryResult.map((item) => (
								<div
									key={item.node.id}
									className="hover:shadow-lg m-4 h-full text-left rounded-lg transition-all border-x border-y border-gray-100 text-ellipsis overflow-hidden"
								>
									<div>
										<Image
											src={item.node.thumbnail.url}
											layout="responsive"
											width="50px"
											height="50px"
										></Image>
									</div>
									<div className="m-4">
										<h2 className="text-3xl font-bold"> {item.node.name} </h2>
										<p className="text-base font-light py-5">
											{item.node.tagline}
										</p>
									</div>
								</div>
							))}
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				Built by Lai Jian Shin for <b className="px-1">WeMakeApp</b>
			</footer>
		</div>
	);
}
